global:
  scrape_interval: 5s  # How often to scrape targets by default.

scrape_configs:
  - job_name: 'node_exporter'  # Name of the scrape job.
    static_configs:
      - targets: ['localhost:9100']  # Target where Node Exporter is running.
